// <======== Exporting Icons ========>
export const Icons = {
    HomeIcon: require('@/assets/icons/home-icon.png'),
    SearchIcon: require('@/assets/icons/search-icon.png'),
    SavedIcon: require('@/assets/icons/saved-icon.png'),
    ProfileIcon: require('@/assets/icons/profile-icon.png'),
    StarIcon: require('@/assets/icons/star-icon.png'),
    TrendingIcon: require('@/assets/icons/trending-icon.png'),
    ArrowRightIcon: require('@/assets/icons/arrow-right-icon.png'),
    BookmarkIcon: require('@/assets/icons/bookmark-icon.png'),
    BookmarkFilledIcon: require('@/assets/icons/bookmark-filled-icon.png'),
    NotificationIcon: require('@/assets/icons/notification-icon.png'),
    EditIcon: require('@/assets/icons/edit-icon.png'),
    ChevronRightIcon: require('@/assets/icons/chevron-right-icon.png'),
    SecurityIcon: require('@/assets/icons/security-icon.png'),
    LanguageIcon: require('@/assets/icons/language-icon.png'),
    HelpCenterIcon: require('@/assets/icons/help-center-icon.png'),
    InviteFriendsIcon: require('@/assets/icons/invite-friends-icon.png'),
    LogoutIcon: require('@/assets/icons/logout-icon.png'),
};